export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Banksite</title>
      </head>
      <body>
        <header>
          <nav>
            <a href="/">Hem</a>
            <a href="/signup">Registrera</a>
            <a href="/login">Logga in</a>
            <a href="/dashboard">Dashboard</a>
          </nav>
        </header>
        <main>{children}</main>
        <footer>
          <p>&copy; 2024 Banksite. Alla rättigheter förbehållna.</p>
        </footer>
      </body>
    </html>
  );
}
